title: "Introduction to cardiac signal analysis"
logo: images/bookLogo.png

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

# Information about where the book exists on the web
repository:
  url                       : https://github.com/embodied-computation-group/systole  # Online location of your book
  path_to_book              : notebook/  # Optional path to your book, relative to the repository root
  branch                    : dev  # Which branch of the repository should be used when creating links (optional)
launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic"
  colab_url: "https://colab.research.google.com"